For this exercises we have to build a processing pipeline that processes the movies dataset. Its not a matter of copy pasting code, but of taking decisions on how to deal with each variable.

### We load the dataset

In [1]:
import pandas as pd
import numpy as np

movies = pd.read_csv("data/movies.1.initial_process.csv")
movies = movies[movies.status=="Released"]
del movies["status"]
movies.head()

,belongs_to_collection,budget,genre,original_language,popularity,production_company,production_country,release_date,revenue,runtime,title,vote_average,vote_count
0,Father of the Bride Collection,NaN,Comedy,en,8.387519,Sandollar Productions,United States of America,1995-02-10,76578911.0,106.0,Father of the Bride Part II,5.7,173.0
1,NaN,NaN,Drama,en,0.894647,Miramax,South Africa,1995-12-15,676525.0,106.0,"Cry, the Beloved Country",6.7,13.0
2,Friday Collection,3500000.0,Comedy,en,14.569650,New Line Cinema,United States of America,1995-04-26,28215918.0,91.0,Friday,7.0,513.0
3,NaN,NaN,Comedy,en,8.963037,Paramount Pictures,United States of America,1996-02-01,32.0,87.0,Black Sheep,6.0,124.0
4,NaN,12000000.0,Comedy,en,9.592265,Universal Pictures,United States of America,1996-02-16,41205099.0,92.0,Happy Gilmore,6.5,767.0

In [2]:
#check the data types of all the columns here and see the types of pipelines you can use
movies.dtypes

belongs_to_collection     object
budget                   float64
genre                     object
original_language         object
popularity               float64
production_company        object
production_country        object
release_date              object
revenue                  float64
runtime                  float64
title                     object
vote_average             float64
vote_count               float64
dtype: object

In [3]:
#Check the columns of the numerical dataframes that have a null value, and count them 
movies.isnull().values.any()
null_columns=movies.columns[movies.isnull().any()]
movies[null_columns].isnull().sum()

belongs_to_collection    1155
budget                    580
genre                      46
production_company        200
production_country         98
revenue                   137
runtime                     7
dtype: int64

This shows that the revenue has some values that are null. How shall we handle them? We drop those

In [4]:
movies = movies[movies.revenue > 0]
movies.head(50)

,belongs_to_collection,budget,genre,original_language,popularity,production_company,production_country,release_date,revenue,runtime,title,vote_average,vote_count
0,Father of the Bride Collection,NaN,Comedy,en,8.387519,Sandollar Productions,United States of America,1995-02-10,76578911.0,106.0,Father of the Bride Part II,5.7,173.0
1,NaN,NaN,Drama,en,0.894647,Miramax,South Africa,1995-12-15,676525.0,106.0,"Cry, the Beloved Country",6.7,13.0
2,Friday Collection,3500000.0,Comedy,en,14.569650,New Line Cinema,United States of America,1995-04-26,28215918.0,91.0,Friday,7.0,513.0
3,NaN,NaN,Comedy,en,8.963037,Paramount Pictures,United States of America,1996-02-01,32.0,87.0,Black Sheep,6.0,124.0
4,NaN,12000000.0,Comedy,en,9.592265,Universal Pictures,United States of America,1996-02-16,41205099.0,92.0,Happy Gilmore,6.5,767.0
5,NaN,NaN,Comedy,en,0.540436,NaN,United States of America,1995-09-15,209935.0,86.0,Man of the Year,3.8,2.0
6,NaN,31000000.0,Comedy,en,6.499680,United Artists,United States of America,1996-03-08,185260553.0,117.0,The Birdcage,6.7,303.0
7,NaN,52000000.0,Drama,en,18.761467,Imagine Entertainment,United States of America,1995-06-30,355237933.0,140.0,Apollo 13,7.3,1637.0
8,Brooklyn Cigar Store Collection,2000000.0,Comedy,en,11.528147,Miramax Films,United States of America,1995-09-15,1275000.0,83.0,Blue in the Face,6.8,28.0
9,NaN,NaN,Documentary,en,3.620388,Superior Pictures,United States of America,1994-09-10,3174695.0,119.0,Crumb,7.6,71.0
10,NaN,90000000.0,Science Fiction,en,8.184815,Hollywood Pictures,United States of America,1995-06-30,113493481.0,96.0,Judge Dredd,5.4,643.0
11,NaN,NaN,Comedy,en,8.482834,Twentieth Century Fox Film Corporation,United States of America,1995-07-12,69660733.0,103.0,Nine Months,5.5,171.0
12,NaN,150000.0,Comedy,en,1.165039,Party Productions,United States of America,1995-06-09,472370.0,94.0,Party Girl,5.8,14.0
13,NaN,NaN,Comedy,en,3.743212,Spring Creek Productions,United States of America,1995-08-04,50892160.0,106.0,Something to Talk About,5.7,60.0
14,NaN,14000000.0,Thriller,en,1.820419,Hollywood Pictures,United States of America,1995-09-08,5780000.0,99.0,The Tie That Binds,4.6,9.0
15,NaN,NaN,Comedy,en,7.653446,Universal Pictures,United States of America,1995-09-07,47774193.0,105.0,"To Wong Foo, Thanks for Everything! Julie Newmar",6.3,117.0
16,NaN,10000000.0,Comedy,en,6.638116,Jack Giarraputo Productions,United States of America,1995-02-10,26488734.0,89.0,Billy Madison,6.2,464.0
17,Clerks Collection,27000.0,Comedy,en,10.513367,Miramax Films,United States of America,1994-09-13,3151130.0,92.0,Clerks,7.4,769.0
18,Dumb and Dumber Collection,16000000.0,Comedy,en,9.844558,New Line Cinema,United States of America,1994-12-16,247275374.0,107.0,Dumb and Dumber,6.5,1894.0
19,NaN,700000.0,Documentary,en,9.476660,Fine Line Features,United States of America,1994-09-12,7830611.0,171.0,Hoop Dreams,7.7,91.0
20,NaN,17000000.0,Drama,en,7.698526,Paramount Pictures,United States of America,1995-03-17,7603766.0,106.0,Losing Isaiah,6.4,28.0
21,Once were Warriors Collection,NaN,Drama,en,4.025276,Avalon Studios,New Zealand,1994-09-02,2201126.0,99.0,Once Were Warriors,7.6,106.0
22,Swan Princess Series,35000000.0,Animation,en,8.910462,Rich Animation Studios,United States of America,1994-11-18,9771658.0,89.0,The Swan Princess,6.5,251.0
23,NaN,NaN,Comedy,en,11.971318,Paramount Pictures,United States of America,1995-03-31,32648673.0,97.0,Tommy Boy,6.8,321.0
24,NaN,NaN,Drama,en,2.583363,Regency Enterprises,United States of America,1994-12-02,1007583.0,128.0,Cobb,6.1,29.0
25,NaN,11500000.0,Drama,en,6.514592,Universal Pictures,United States of America,1994-02-18,20079850.0,99.0,Reality Bites,6.5,180.0
26,NaN,NaN,Comedy,en,1.679042,Touchstone Pictures,United States of America,1994-01-07,3662459.0,80.0,Cabin Boy,4.9,28.0
27,NaN,NaN,Comedy,en,13.696394,Donner/Shuler-Donner Productions,United States of America,1993-05-07,63000000.0,110.0,Dave,6.3,205.0
28,NaN,NaN,Comedy,en,6.071466,Hollywood Pictures,United States of America,1994-08-12,28881266.0,91.0,In the Army Now,4.7,54.0
29,NaN,NaN,Drama,en,5.997712,Icon Entertainment International,United States of America,1993-08-25,24760338.0,114.0,The Man without a Face,6.2,125.0
30,The Karate Kid Collection,12000000.0,Adventure,en,9.969700,Columbia Pictures Corporation,United States of America,1994-07-18,15826984.0,107.0,The Next Karate Kid,4.8,202.0
31,NaN,26000000.0,Drama,en,13.373006,TriStar Pictures,United States of America,1993-12-22,206678440.0,125.0,Philadelphia,7.6,1019.0
32,NaN,NaN,Drama,en,3.199976,Touchstone Pictures,United States of America,1993-09-24,23042200.0,112.0,The Program,6.0,28.0
33,NaN,11000000.0,Comedy,en,5.868677,Touchstone Pictures,United States of America,1994-03-09,11439193.0,97.0,The Ref,6.7,99.0
34,NaN,12000000.0,Drama,en,5.914833,TriStar Pictures,United States of America,1993-09-17,22750363.0,114.0,Rudy,7.2,187.0
35,NaN,NaN,Drama,en,12.048587,Mirage Enterprises,United States of America,1993-08-13,7266383.0,110.0,Searching for Bobby Fischer,7.3,100.0
36,Candyman Collection,NaN,Horror,en,4.983552,Propaganda Films,United States of America,1995-03-17,13940383.0,93.0,Candyman: Farewell to the Flesh,5.0,64.0
37,NaN,12000000.0,Comedy,en,4.405169,Fox Searchlight Pictures,United States of America,1996-03-22,4939939.0,108.0,Girl 6,5.7,17.0
38,NaN,NaN,Comedy,de,0.002229,Senator Film Produktion,Germany,1996-03-14,65335.0,NaN,Happy Weekend,0.0,0.0
39,DragonHeart Collection,57000000.0,Fantasy,en,23.636590,Universal Pictures,United States of America,1996-05-31,115267375.0,103.0,DragonHeart,6.4,553.0
40,The Apu Collection,NaN,Drama,bn,3.900709,Government of West Bengal,India,1955-08-26,536364.0,125.0,Pather Panchali,7.9,63.0
41,The Apu Collection,NaN,Drama,bn,2.381806,Satyajit Ray Productions,India,1959-05-01,16000.0,117.0,The World of Apu,8.2,40.0
42,NaN,9000000.0,Science Fiction,en,14.304205,Paramount Pictures,United States of America,1968-10-10,2500000.0,98.0,Barbarella,5.7,149.0
43,NaN,27000000.0,Comedy,en,11.633347,Motion Picture Corporation of America,United States of America,1996-07-04,25023434.0,113.0,Kingpin,6.7,248.0
44,NaN,26000000.0,Comedy,en,10.177303,Scott Rudin Productions,United States of America,1996-09-20,116400000.0,102.0,The First Wives Club,6.5,172.0
45,NaN,NaN,Comedy,en,4.220058,TriStar Pictures,United States of America,1996-10-25,21302121.0,86.0,High School High,5.4,51.0
46,NaN,1752000.0,Drama,en,11.709777,Paramount Pictures,United States of America,1950-08-10,5000000.0,110.0,Sunset Boulevard,8.2,533.0
47,NaN,1400000.0,Drama,en,12.063080,Twentieth Century Fox Film Corporation,United States of America,1950-11-09,63463.0,138.0,All About Eve,8.0,367.0
48,NaN,1.0,Drama,en,6.428830,Warner Bros.,United States of America,1955-03-09,5.0,115.0,East of Eden,7.5,163.0
49,Living Dead Collection,114000.0,Horror,en,14.384198,Laurel Group,United States of America,1968-10-01,30000000.0,96.0,Night of the Living Dead,7.5,591.0

In [5]:
target_var = "revenue"
numerical_cols = movies.drop(columns=target_var).select_dtypes(np.number).columns

### Create a Pipeline that process the dataset. You have to make sure you deal accordingly with numerical, categorical and text variables.

In [59]:
#for the numerical datatypes
from sklearn import preprocessing, feature_extraction

#use the imputer's to fill up any missing data with the mean
imputer = preprocessing.Imputer(strategy="mean")
scaler = preprocessing.StandardScaler()

In [36]:
from sklearn.pipeline import make_pipeline

In [37]:
numerical_pipeline = make_pipeline(imputer,scaler)

In [38]:
numerical_pipeline

Pipeline(memory=None,
     steps=[('imputer', Imputer(axis=0, copy=True, missing_values='NaN', strategy='most_frequent',
    verbose=0)), ('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True))])

In [39]:
numerical_pipeline.fit_transform(movies[numerical_cols])

array([[ 0.08021286,  0.3814959 ,  0.10466098, -0.3267635 , -0.22703182],
       [ 0.08021286, -1.03915849,  0.10466098,  0.43720626, -0.53866313],
       [-0.8874011 ,  1.55363278, -0.62659035,  0.66639719,  0.43518473],
       ...,
       [ 0.08021286, -1.12276277, -0.28533973, -1.54911512, -0.54450622],
       [-0.15436022,  0.65775164,  0.15341107,  0.28441231,  3.12495252],
       [ 0.08021286,  0.41578691, -0.38283991,  0.36080929,  0.04564558]])

### Transform the dataset

In [40]:
from sklearn.base import BaseEstimator

class ColumnSelector(BaseEstimator):
    def __init__(self, cols=None, drop_axis=False):
        self.cols = cols
        self.drop_axis = drop_axis

    def fit_transform(self, X, y=None):
        return self.transform(X=X, y=y)

    def transform(self, X, y=None):
        if hasattr(X, 'loc'):
            #only pandas dataframes have the method loc
            t = X.loc[:, self.cols].values
        else:
            # its a numpy array
            t = X[:, self.cols]

        if t.shape[-1] == 1 and self.drop_axis:
            t = t.reshape(-1)
        if len(t.shape) == 1 and not self.drop_axis:
            t = t[:, np.newaxis]
        return t

    def fit(self, X, y=None):
        return self

In [41]:
numerical_col_selector = ColumnSelector(cols=numerical_cols)

In [42]:
numerical_col_selector.fit_transform(movies)

array([[             nan,   8.38751900e+00,   1.06000000e+02,
          5.70000000e+00,   1.73000000e+02],
       [             nan,   8.94647000e-01,   1.06000000e+02,
          6.70000000e+00,   1.30000000e+01],
       [  3.50000000e+06,   1.45696500e+01,   9.10000000e+01,
          7.00000000e+00,   5.13000000e+02],
       ...,
       [             nan,   4.53698000e-01,   9.80000000e+01,
          4.10000000e+00,   1.00000000e+01],
       [  1.60000000e+07,   9.84455800e+00,   1.07000000e+02,
          6.50000000e+00,   1.89400000e+03],
       [             nan,   8.56837800e+00,   9.60000000e+01,
          6.60000000e+00,   3.13000000e+02]])

In [43]:
numerical_pipeline =  make_pipeline( numerical_col_selector, imputer, scaler)

In [44]:
numerical_pipeline.fit_transform(movies)

array([[ 0.08021286,  0.3814959 ,  0.10466098, -0.3267635 , -0.22703182],
       [ 0.08021286, -1.03915849,  0.10466098,  0.43720626, -0.53866313],
       [-0.8874011 ,  1.55363278, -0.62659035,  0.66639719,  0.43518473],
       ...,
       [ 0.08021286, -1.12276277, -0.28533973, -1.54911512, -0.54450622],
       [-0.15436022,  0.65775164,  0.15341107,  0.28441231,  3.12495252],
       [ 0.08021286,  0.41578691, -0.38283991,  0.36080929,  0.04564558]])

##Make the movie name a text column, to check the weightage of the words in the title

In [45]:
#text_col --> movie name
text_col = ["title"]

In [46]:
movies[text_col].head(5)

                         title
0  Father of the Bride Part II
1     Cry, the Beloved Country
2                       Friday
3                  Black Sheep
4                Happy Gilmore

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer 
from mlxtend.preprocessing import DenseTransformer

text_pipeline = make_pipeline(
    #ColumnSelector only works on a single column
  ColumnSelector(cols=text_col, drop_axis=True),
  TfidfVectorizer(),
    DenseTransformer()
)

In [48]:
text_pipeline.fit_transform(movies)

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [49]:
#Categorical Pipeline on the languages, genre, production country

from category_encoders import OneHotEncoder

In [50]:
categorical_col = ["original_language", "genre", "production_country"]

In [51]:
categorical_pipeline = make_pipeline(
    ColumnSelector(cols=categorical_col),
    OneHotEncoder()
)

categorical_pipeline.fit_transform(movies)[:5]

,0_1,0_2,0_3,0_4,0_5,0_6,0_7,0_8,0_9,0_10,...,2_25,2_26,2_27,2_28,2_29,2_30,2_31,2_32,2_33,2_-1
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [52]:
#Attempt 1, try a union

from sklearn.pipeline import make_union

In [53]:
processing_pipeline = make_union(numerical_pipeline,
    #text_pipeline,
    categorical_pipeline)

In [54]:
processing_pipeline

FeatureUnion(n_jobs=1,
       transformer_list=[('pipeline-1', Pipeline(memory=None,
     steps=[('columnselector', ColumnSelector(cols=Index(['budget', 'popularity', 'runtime', 'vote_average', 'vote_count'], dtype='object'),
        drop_axis=False)), ('imputer', Imputer(axis=0, copy=True, missing_values='NaN', strategy='most_f...e_unknown='impute',
       impute_missing=True, return_df=True, use_cat_names=False, verbose=0))]))],
       transformer_weights=None)

In [55]:
processing_pipeline.fit_transform(movies)

array([[ 0.08021286,  0.3814959 ,  0.10466098, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.08021286, -1.03915849,  0.10466098, ...,  0.        ,
         0.        ,  0.        ],
       [-0.8874011 ,  1.55363278, -0.62659035, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.08021286, -1.12276277, -0.28533973, ...,  0.        ,
         0.        ,  0.        ],
       [-0.15436022,  0.65775164,  0.15341107, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.08021286,  0.41578691, -0.38283991, ...,  0.        ,
         0.        ,  0.        ]])

### Create a Ridge estimator to predict a movies revenue based on the other features. What is the optimal value of alpha to minimize the RMSE? *Hint*: You can use validation curves to figure it out.

In [56]:
from sklearn.linear_model import LinearRegression

estimator = LinearRegression()
estimator_pipeline = make_pipeline(
    processing_pipeline,
    estimator
)

In [57]:
estimator_pipeline.fit(movies, movies[target_var])

#Then this means that the revenue has some Nan values. check it out

Pipeline(memory=None,
     steps=[('featureunion', FeatureUnion(n_jobs=1,
       transformer_list=[('pipeline-1', Pipeline(memory=None,
     steps=[('columnselector', ColumnSelector(cols=Index(['budget', 'popularity', 'runtime', 'vote_average', 'vote_count'], dtype='object'),
        drop_axis=False)), ('imputer', Imputer(axi... ('linearregression', LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False))])

In [58]:
list(estimator_pipeline.predict(movies)[:])

[36974592.0,
 675840.0,
 40173568.0,
 30261248.0,
 68952064.0,
 21417984.0,
 62001152.0,
 173121536.0,
 2818048.0,
 16920576.0,
 126296064.0,
 36073472.0,
 3592192.0,
 30142464.0,
 -296960.0,
 33587200.0,
 44906496.0,
 56508416.0,
 157143040.0,
 4558848.0,
 14696448.0,
 13688832.0,
 56682496.0,
 46178304.0,
 23080960.0,
 18776064.0,
 23048192.0,
 39096320.0,
 25399296.0,
 26681344.0,
 38830080.0,
 99020800.0,
 19929088.0,
 21843968.0,
 23347200.0,
 23599104.0,
 24385536.0,
 18354176.0,
 14757888.0,
 100499456.0,
 2230272.0,
 -90112.0,
 -8192.0,
 51458048.0,
 43155456.0,
 25550848.0,
 35627008.0,
 27873280.0,
 8675328.0,
 40785920.0,
 54366208.0,
 139591680.0,
 1081344.0,
 14589952.0,
 94404608.0,
 27181056.0,
 105213952.0,
 21495808.0,
 56242176.0,
 23437312.0,
 21209088.0,
 -1075200.0,
 10139648.0,
 6864896.0,
 -12869632.0,
 212242432.0,
 36851712.0,
 145342464.0,
 88567808.0,
 43245568.0,
 215089152.0,
 58793984.0,
 35704832.0,
 89313280.0,
 64610304.0,
 7911424.0,
 26996736.0,
 74555392.0,
 86413312.0,
 17580032.0,
 125792256.0,
 28168192.0,
 40423424.0,
 23416832.0,
 153821184.0,
 28768256.0,
 34598912.0,
 5373952.0,
 11413504.0,
 31350784.0,
 7221248.0,
 22116352.0,
 78714880.0,
 45670400.0,
 -4575232.0,
 37552128.0,
 105533440.0,
 38305792.0,
 35663872.0,
 9777152.0,
 24739840.0,
 -2910208.0,
 2957312.0,
 3395584.0,
 21409792.0,
 129179648.0,
 37797888.0,
 57532416.0,
 153448448.0,
 26034176.0,
 42831872.0,
 10211328.0,
 71831552.0,
 42131456.0,
 34508800.0,
 19972096.0,
 38113280.0,
 44048384.0,
 -9295872.0,
 22921216.0,
 46182400.0,
 60588032.0,
 17178624.0,
 26046464.0,
 25051136.0,
 107925504.0,
 59011072.0,
 21899264.0,
 17551360.0,
 30412800.0,
 673792.0,
 27439104.0,
 241987584.0,
 62468096.0,
 -9011200.0,
 14917632.0,
 4648960.0,
 71557120.0,
 74956800.0,
 95932416.0,
 86659072.0,
 32102400.0,
 72540160.0,
 79847424.0,
 56678400.0,
 6256640.0,
 23687168.0,
 39616512.0,
 14020608.0,
 31023104.0,
 32018432.0,
 11288576.0,
 9543680.0,
 14909440.0,
 598016.0,
 51937280.0,
 29114368.0,
 85090304.0,
 1107968.0,
 14204928.0,
 30795776.0,
 19763200.0,
 43970560.0,
 -5492736.0,
 25989120.0,
 3477504.0,
 82763776.0,
 41365504.0,
 6547456.0,
 49160192.0,
 258859008.0,
 1531904.0,
 31227904.0,
 105668608.0,
 14159872.0,
 5400576.0,
 -5132288.0,
 -9601024.0,
 31625216.0,
 63700992.0,
 10616832.0,
 103804928.0,
 12861440.0,
 23959552.0,
 24965120.0,
 25600000.0,
 21381120.0,
 14688256.0,
 7274496.0,
 41263104.0,
 35577856.0,
 59056128.0,
 18597888.0,
 16015360.0,
 30824448.0,
 40869888.0,
 44462080.0,
 8712192.0,
 110723072.0,
 18731008.0,
 95295488.0,
 23941120.0,
 86478848.0,
 -1847296.0,
 -13205504.0,
 27893760.0,
 19914752.0,
 13135872.0,
 91082752.0,
 77008896.0,
 28459008.0,
 12587008.0,
 44834816.0,
 32575488.0,
 -9338880.0,
 8257536.0,
 -3796992.0,
 110137344.0,
 26519552.0,
 108421120.0,
 124620800.0,
 37728256.0,
 25649152.0,
 20035584.0,
 19261440.0,
 2899968.0,
 27705344.0,
 28758016.0,
 35082240.0,
 4966400.0,
 20996096.0,
 51720192.0,
 10743808.0,
 13148160.0,
 34717696.0,
 -7096320.0,
 -2228224.0,
 6164480.0,
 6574080.0,
 -14209024.0,
 129419264.0,
 171372544.0,
 125190144.0,
 9101312.0,
 2998272.0,
 2347008.0,
 59215872.0,
 18919424.0,
 12193792.0,
 73986048.0,
 16396288.0,
 89800704.0,
 32337920.0,
 28913664.0,
 74133504.0,
 119533568.0,
 64233472.0,
 16506880.0,
 34656256.0,
 49303552.0,
 68497408.0,
 26855424.0,
 71569408.0,
 19689472.0,
 -1089536.0,
 22507520.0,
 30273536.0,
 63238144.0,
 8433664.0,
 -10993664.0,
 27385856.0,
 14577664.0,
 27408384.0,
 34887680.0,
 20819968.0,
 24045568.0,
 28397568.0,
 27652096.0,
 35080192.0,
 32960512.0,
 14823424.0,
 12754944.0,
 85245952.0,
 86016.0,
 -12929024.0,
 21581824.0,
 37269504.0,
 11599872.0,
 -7475200.0,
 23969792.0,
 60620800.0,
 31547392.0,
 19480576.0,
 32616448.0,
 -5464064.0,
 27144192.0,
 24428544.0,
 22310912.0,
 8892416.0,
 17152000.0,
 61554688.0,
 -4665344.0,
 15835136.0,
 -3309568.0,
 31064064.0,
 28098560.0,
 40040448.0,
 48691200.0,
 31119360.0,
 153993216.0,
 61161472.0,
 28844032.0,
 24203264.0,
 24313856.0,
 1425408.0,
 7131136.0,
 18776064.0,
 36315136.0,
 8912896.0,
 7077888.0,
 27037696.0,
 7766016.0,
 -4141056.0,
 5945344.0,
 13164544.0,
 5365760.0,
 -6262784.0,
 -13500416.0,
 8495104.0,
 18939904.0,
 21927936.0,
 18911232.0,
 22654976.0,
 8826880.0,
 23928832.0,
 17522688.0,
 25419776.0,
 14260224.0,
 14964736.0,
 12800000.0,
 160927744.0,
 -2306048.0,
 33536000.0,
 29294592.0,
 47423488.0,
 20480.0,
 54792192.0,
 -897024.0,
 1265664.0,
 64798720.0,
 -135168.0,
 38531072.0,
 14493696.0,
 7809024.0,
 7675904.0,
 152807424.0,
 26349568.0,
 5259264.0,
 17543168.0,
 -14004224.0,
 16662528.0,
 17334272.0,
 31469568.0,
 9383936.0,
 17416192.0,
 33034240.0,
 21417984.0,
 20815872.0,
 77860864.0,
 59793408.0,
 96247808.0,
 34938880.0,
 37175296.0,
 12374016.0,
 9846784.0,
 36708352.0,
 -2670592.0,
 20254720.0,
 23318528.0,
 68737024.0,
 14630912.0,
 10799104.0,
 29833216.0,
 15142912.0,
 57638912.0,
 41267200.0,
 119275520.0,
 23330816.0,
 -1454080.0,
 25956352.0,
 243154944.0,
 67620864.0,
 28422144.0,
 18829312.0,
 1511424.0,
 29429760.0,
 38682624.0,
 28766208.0,
 -14913536.0,
 10620928.0,
 2932736.0,
 79106048.0,
 22093824.0,
 30363648.0,
 98078720.0,
 2945024.0,
 7157760.0,
 21463040.0,
 2189312.0,
 -331776.0,
 4214784.0,
 77676544.0,
 93689856.0,
 38842368.0,
 90497024.0,
 192987136.0,
 -4538368.0,
 1458176.0,
 31088640.0,
 11214848.0,
 1171456.0,
 22960128.0,
 20039680.0,
 -1294336.0,
 37273600.0,
 17113088.0,
 24680448.0,
 15824896.0,
 18616320.0,
 42237952.0,
 11702272.0,
 21520384.0,
 95377408.0,
 37728256.0,
 42467328.0,
 126976.0,
 139268096.0,
 23932928.0,
 4132864.0,
 20578304.0,
 27181056.0,
 39370752.0,
 1009664.0,
 -1716224.0,
 -13209600.0,
 -1052672.0,
 -5120000.0,
 -593920.0,
 10805248.0,
 -2777088.0,
 1011712.0,
 11644928.0,
 15425536.0,
 17547264.0,
 29548544.0,
 10190848.0,
 16818176.0,
 -1044480.0,
 26877952.0,
 -11268096.0,
 22761472.0,
 1904640.0,
 29913088.0,
 6516736.0,
 16384.0,
 15925248.0,
 -8368128.0,
 121438208.0,
 -12234752.0,
 9523200.0,
 212551680.0,
 243404800.0,
 21024768.0,
 26386432.0,
 25088000.0,
 16388096.0,
 5189632.0,
 -3993600.0,
 29822976.0,
 598016.0,
 36634624.0,
 21737472.0,
 15073280.0,
 4124672.0,
 5230592.0,
 59652096.0,
 22515712.0,
 95457280.0,
 1187840.0,
 -13938688.0,
 12341248.0,
 20787200.0,
 167583744.0,
 39145472.0,
 24956928.0,
 46112768.0,
 22413312.0,
 45457408.0,
 -1867776.0,
 93093888.0,
 14483456.0,
 52903936.0,
 352256.0,
 -8331264.0,
 -598016.0,
 5783552.0,
 100749312.0,
 106192896.0,
 155049984.0,
 29884416.0,
 40951808.0,
 15171584.0,
 67624960.0,
 39792640.0,
 30064640.0,
 34643968.0,
 29986816.0,
 84955136.0,
 34947072.0,
 10952704.0,
 19238912.0,
 102539264.0,
 -4775936.0,
 20070400.0,
 36868096.0,
 -11505664.0,
 4182016.0,
 121094144.0,
 315392.0,
 242092032.0,
 11169792.0,
 33820672.0,
 56127488.0,
 35266560.0,
 32112640.0,
 -1437696.0,
 135460864.0,
 13991936.0,
 20674560.0,
 -270336.0,
 7897088.0,
 34668544.0,
 80523264.0,
 83525632.0,
 97468416.0,
 35938304.0,
 -6610944.0,
 12888064.0,
 23117824.0,
 14557184.0,
 36085760.0,
 98656256.0,
 -1294336.0,
 30404608.0,
 -3444736.0,
 3096576.0,
 -15814656.0,
 57077760.0,
 43712512.0,
 72153088.0,
 -3895296.0,
 -5664768.0,
 4403200.0,
 41869312.0,
 -23531520.0,
 3985408.0,
 18509824.0,
 -17158144.0,
 25255936.0,
 16502784.0,
 -5648384.0,
 179924992.0,
 21340160.0,
 8880128.0,
 39272448.0,
 52842496.0,
 135819264.0,
 -18618368.0,
 35856384.0,
 100139008.0,
 18532352.0,
 9510912.0,
 3178496.0,
 5890048.0,
 647168.0,
 145956864.0,
 25212928.0,
 44568576.0,
 48533504.0,
 56991744.0,
 26148864.0,
 40415232.0,
 -9814016.0,
 3297280.0,
 17031168.0,
 1773568.0,
 -2064384.0,
 26501120.0,
 48513024.0,
 -12226560.0,
 28590080.0,
 7172096.0,
 10313728.0,
 10989568.0,
 6514688.0,
 48918528.0,
 21442560.0,
 4419584.0,
 151781376.0,
 -20676608.0,
 9998336.0,
 3401728.0,
 24238080.0,
 82083840.0,
 39526400.0,
 74493952.0,
 -3207168.0,
 19396608.0,
 5713920.0,
 21258240.0,
 205623296.0,
 214495232.0,
 7913472.0,
 96518144.0,
 33495040.0,
 9461760.0,
 12914688.0,
 58265600.0,
 85372928.0,
 8310784.0,
 68134912.0,
 123392000.0,
 27062272.0,
 77045760.0,
 36579328.0,
 20631552.0,
 -356352.0,
 72808448.0,
 16166912.0,
 7966720.0,
 23879680.0,
 22245376.0,
 35407872.0,
 21807104.0,
 22790144.0,
 22245376.0,
 36098048.0,
 38230016.0,
 15341568.0,
 20211712.0,
 63008768.0,
 41218048.0,
 36675584.0,
 146544640.0,
 85966848.0,
 -10745856.0,
 34684928.0,
 1441792.0,
 71688192.0,
 21860352.0,
 34619392.0,
 10854400.0,
 27846656.0,
 45821952.0,
 20275200.0,
 101969920.0,
 144576512.0,
 -6086656.0,
 8175616.0,
 40128512.0,
 73728.0,
 16506880.0,
 92778496.0,
 389120.0,
 36990976.0,
 211918848.0,
 118069248.0,
 84586496.0,
 -4567040.0,
 -27627520.0,
 290308096.0,
 172331008.0,
 109256704.0,
 -3997696.0,
 5783552.0,
 43413504.0,
 -2981888.0,
 29847552.0,
 9027584.0,
 21602304.0,
 131235840.0,
 28741632.0,
 24195072.0,
 26345472.0,
 9412608.0,
 167665664.0,
 8757248.0,
 15314944.0,
 -2785280.0,
 26144768.0,
 -290816.0,
 27389952.0,
 5992448.0,
 24653824.0,
 32112640.0,
 86700032.0,
 19855360.0,
 42874880.0,
 13492224.0,
 6053888.0,
 19712000.0,
 15441920.0,
 393216.0,
 29726720.0,
 -4096.0,
 -1150976.0,
 363315200.0,
 9019392.0,
 35115008.0,
 -3846144.0,
 139796480.0,
 93970432.0,
 7942144.0,
 8474624.0,
 13260800.0,
 12697600.0,
 9060352.0,
 9629696.0,
 115855360.0,
 47538176.0,
 18141184.0,
 -9555968.0,
 21520384.0,
 48439296.0,
 12539904.0,
 9357312.0,
 153784320.0,
 73754624.0,
 425984.0,
 8034304.0,
 18309120.0,
 23508992.0,
 50008064.0,
 28942336.0,
 63803392.0,
 130531328.0,
 28454912.0,
 47800320.0,
 94949376.0,
 10151936.0,
 7157760.0,
 52146176.0,
 1855488.0,
 4329472.0,
 7176192.0,
 20062208.0,
 17162240.0,
 20828160.0,
 4968448.0,
 64221184.0,
 9576448.0,
 3323904.0,
 21575680.0,
 22835200.0,
 41058304.0,
 177668096.0,
 41197568.0,
 71045120.0,
 16760832.0,
 199663616.0,
 -2428928.0,
 68005888.0,
 25985024.0,
 14286848.0,
 139214848.0,
 20848640.0,
 63758336.0,
 13377536.0,
 114380800.0,
 8970240.0,
 25376768.0,
 87097344.0,
 -14925824.0,
 16150528.0,
 -14192640.0,
 9961472.0,
 13467648.0,
 32923648.0,
 28203008.0,
 3510272.0,
 44750848.0,
 66310144.0,
 -2224128.0,
 17227776.0,
 22773760.0,
 209424384.0,
 22462464.0,
 51580928.0,
 13709312.0,
 19181568.0,
 7237632.0,
 6701056.0,
 65343488.0,
 110551040.0,
 19746816.0,
 6250496.0,
 44120064.0,
 -798720.0,
 13754368.0,
 30441472.0,
 -3272704.0,
 -15589376.0,
 5697536.0,
 7018496.0,
 63074304.0,
 18194432.0,
 6017024.0,
 5992448.0,
 37089280.0,
 67563520.0,
 93638656.0,
 10768384.0,
 2834432.0,
 86577152.0,
 6416384.0,
 12890112.0,
 141942784.0,
 98566144.0,
 76795904.0,
 53248.0,
 87523328.0,
 1069056.0,
 193355776.0,
 326422528.0,
 19304448.0,
 69132288.0,
 14577664.0,
 34361344.0,
 -3393536.0,
 40267776.0,
 17264640.0,
 174696448.0,
 38137856.0,
 90081280.0,
 15433728.0,
 107667456.0,
 1810432.0,
 47620096.0,
 4284416.0,
 13058048.0,
 16547840.0,
 16986112.0,
 -7356416.0,
 17367040.0,
 24133632.0,
 66514944.0,
 2449408.0,
 462848.0,
 92270592.0,
 49037312.0,
 33763328.0,
 70451200.0,
 15675392.0,
 -10813440.0,
 2752512.0,
 128247808.0,
 -10870784.0,
 24774656.0,
 78739456.0,
 29536256.0,
 14491648.0,
 26146816.0,
 16205824.0,
 18194432.0,
 -3653632.0,
 19578880.0,
 46989312.0,
 37470208.0,
 23707648.0,
 21565440.0,
 35311616.0,
 29630464.0,
 18743296.0,
 7520256.0,
 16805888.0,
 45019136.0,
 83136512.0,
 31283200.0,
 37351424.0,
 22421504.0,
 219877376.0,
 21200896.0,
 24920064.0,
 15732736.0,
 57729024.0,
 104079360.0,
 122998784.0,
 4763648.0,
 -3497984.0,
 43417600.0,
 10760192.0,
 -12922880.0,
 913408.0,
 10790912.0,
 -10493952.0,
 154628096.0,
 12812288.0,
 59109376.0,
 298618880.0,
 164034560.0,
 33738752.0,
 108335104.0,
 -679936.0,
 1093632.0,
 108371968.0,
 28803072.0,
 16596992.0,
 17950720.0,
 34197504.0,
 7516160.0,
 33026048.0,
 24694784.0,
 35282944.0,
 27615232.0,
 115666944.0,
 22753280.0,
 156528640.0,
 26112000.0,
 71491584.0,
 6346752.0,
 34623488.0,
 23674880.0,
 127197184.0,
 21901312.0,
 159567872.0,
 14264320.0,
 80121856.0,
 283799552.0,
 3301376.0,
 -10172416.0,
 43900928.0,
 80912384.0,
 14848000.0,
 21876736.0,
 -4509696.0,
 8359936.0,
 -3543040.0,
 7933952.0,
 5935104.0,
 11939840.0,
 16486400.0,
 24698880.0,
 529088512.0,
 6881280.0,
 24649728.0,
 26734592.0,
 15351808.0,
 3090432.0,
 8871936.0,
 4431872.0,
 15134720.0,
 25868288.0,
 31629312.0,
 26173440.0,
 46106624.0,
 13307904.0,
 21782528.0,
 13182976.0,
 29825024.0,
 14034944.0,
 34938880.0,
 -29184000.0,
 7188480.0,
 4599808.0,
 72232960.0,
 4638720.0,
 58214400.0,
 32608256.0,
 41326592.0,
 16461824.0,
 10801152.0,
 36667392.0,
 60440576.0,
 1406976.0,
 616448.0,
 115101696.0,
 17539072.0,
 -3624960.0,
 11565056.0,
 -10657792.0,
 6008832.0,
 13529088.0,
 16662528.0,
 -1445888.0,
 11442176.0,
 -2748416.0,
 7548928.0,
 -13332480.0,
 10182656.0,
 -1499136.0,
 ...]

### Remember when we did exploratory data analyses and we groupd the numerical variables into quintiles? That is a valid technique used in Machine Learning to expand a dataset, it is called [Binning or Bucketing](http://blog.yhat.com/tutorials/5-Feature-Engineering.html).

### Create your own transformer that given a numerical variable and a number of buckets returns the specificed quartile (so if we choose buckets = 4, it would return 1, 2,3 or 4 depending on each observation being on the 1st, 2nd, 3rd or 4th quartile).

### Try putting your bucket transformer into a pipeline to make sure it works, and check if it improves the performance of your model.

**Hint**: You can use `ColumnSelector` as a template, and you can check pandas `qcut` for the actual binning.